version: "3.8"

services:
  db:
    image: postgres:9.6.24-alpine3.15
    container_name: db
    environment:
      - POSTGRES_DB=zloi
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  api:
    image: node:16.13.2-alpine
    container_name: api
    working_dir: /opt/server/
    restart: always
    volumes:
      - ./api:/opt/server/
    entrypoint: npm run dev
    environment:
      - NODE_ENV=dev
      - DB_HOST=db
      - DB_NAME=zloi
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - ADMIN_KEY=1111111111111111
    ports:
      - 3000:3000
    expose:
      - 3000

  admin:
    image: node:16.13.2-alpine
    container_name: admin
    working_dir: /opt/server/
    restart: always
    volumes:
      - ./admin:/opt/server/
    entrypoint: npm run dev
    environment:
      - NODE_ENV=dev
    ports:
      - 8081:8081
    expose:
      - 8081

  web:
    image: node:16.13.2-alpine
    container_name: web
    working_dir: /opt/server/
    restart: always
    volumes:
      - ./web:/opt/server/
    entrypoint: npm run dev
    environment:
      - NODE_ENV=dev
    ports:
      - 8080:8080
    expose:
      - 8080
