version: "3.8"

services:
  db:
    image: postgres:9.6.24-alpine3.15
    container_name: db
    environment:
      - POSTGRES_DB=zloi
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432

  # web:
  #   image: node:16.13.2-alpine
  #   container_name: web
  #   working_dir: /opt/server/
  #   restart: always
  #   volumes:
  #     - ./web:/opt/server/
  #   entrypoint: npm run dev
  #   #env_file: ./.env
  #   environment:
  #     - NODE_ENV=dev
  #     - DB_HOST=db
  #     - DB_NAME=zloi
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=admin
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
