apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zloi-api.fullname" . }}
  labels:
    {{- include "zloi-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zloi-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zloi-api.labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{.Values.image.repository }}/zloi-api:{{.Values.image.tag}}"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
          readinessProbe:
            httpGet:
              path: /health-check
              port: 3000
          ports:
          - containerPort: 3000
          env:
          - name: DB_HOST
            value: {{ .Release.Name }}-postgresql
          - name: DB_NAME
            value: {{ .Values.postgresql.auth.database }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password }}
          - name: ADMIN_KEY
            value: {{ .Values.api.adminKey }}