{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zloi-admin.fullname" . }}
  labels:
    {{- include "zloi-admin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        -  {{ include "zloi-admin.hostname" . }}
      secretName: {{ include "zloi-admin.hostname" . }}-tls
{{- end }}
  rules:
    - host: {{ include "zloi-admin.hostname" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "zloi-admin.fullname" . }}
                port:
                  number: 80
{{- end }}
