apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zloi-space.fullname" . }}
  labels:
    {{- include "zloi-space.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: 0
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  activeDeadlineSeconds: 60
  backoffLimit: 0
  template:
    metadata:
      name: {{ include "zloi-space.fullname" . }}
      labels:
        {{- include "zloi-space.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure      
      initContainers:
      - name: wait-db
        image: alpine:3.6
        —Åommand: ["/bin/sh", "-c", "while ! nc -z {{ .Release.Name }}-postgresql 5432; do sleep 1; done;"]
      containers:
      - name: initDB
        image: {{.Values.image.repository }}/zloi-updater:{{.Values.image.tag}}
        env:
        - name: DB_HOST
          value: {{ .Release.Name }}-postgresql
        - name: DB_NAME
          value: {{ .Values.postgresql.auth.database }}
        - name: DB_USERNAME
          value: {{ .Values.postgresql.auth.username }}
        - name: DB_PASSWORD
          value: {{ .Values.postgresql.auth.password }}
