apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zloi-space.fullname" . }}
  labels:
    {{- include "zloi-space.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "zloi-space.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zloi-space.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{.Values.image.repository }}/{{.Values.image.name}}:{{.Values.image.tag}}"
          livenessProbe:
            httpGet:
              path: /kubernetes/health-check
              port: 8080
          readinessProbe:
            httpGet:
              path: /kubernetes/health-check
              port: 8080
          ports:
          - containerPort: 8080
          env:
          - name: API_URL
            value: http{{ if .Values.ingress.tls }}s{{ end }}://{{.Values.ingress.hostname }}
          - name: DB_HOST
            value: {{ .Release.Name }}-postgresql
          - name: DB_NAME
            value: {{ .Values.postgresql.auth.database }}
          - name: DB_USERNAME
            value: {{ .Values.postgresql.auth.username }}
          - name: DB_PASSWORD
            value: {{ .Values.postgresql.auth.password }}