apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zloi-space.fullname" . }}
  labels:
    {{- include "zloi-space.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zloi-space.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zloi-space.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{.Values.image.repository }}/{{.Values.image.name}}:{{.Values.image.tag}}"
          livenessProbe:
            httpGet:
              path: /kubernetes/health-check
              port: 3000
          readinessProbe:
            httpGet:
              path: /kubernetes/health-check
              port: 3000
          ports:
          - containerPort: 3000
          env:
          - name: API_URL
            value: http{{ if .Values.ingress.tls }}s{{ end }}://{{.Values.ingress.hostname }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          