{{- if .Values.priorityclass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "zloi-space.fullname" . }}
value: {{ .Values.priorityclass.value }}
preemptionPolicy: PreemptLowerPriority
globalDefault: false
{{- end }}
