apiVersion: v1
kind: Service
metadata:
  name: {{ include "zloi-space.fullname" . }}
  labels:
    {{- include "zloi-space.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "zloi-space.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
