tier: dev

image:
  repository: registry.gitlab.com/zl0i/zloi-space
  tag: v1.0

web:
  nameOverride: 'web'
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      cpu: 800m

api:
  nameOverride: 'api'
  replicaCount: 1
  adminKey: ''
  resources:
    requests:
      memory: 128Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m

admin:
  nameOverride: 'admin'
  replicaCount: 1
  resources:
    requests:
      memory: 172Mi
      cpu: 200m
    limits:
      memory: 172Mi
      cpu: 200m

ingress:
  enabled: true
  basehost: 'zloi.space'
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png|json)) {
        add_header Cache-Control "public, max-age=7200";
      }

priorityclass:
  enabled: false
  value: 1000000

postgresql:
  auth:
    postgresPassword: postgres
    username: zloi
    password: zloi
    database: zloi-space
  primary:
    persistence:
      size: 1Gi
